### ISSUE TITLE
Error in evaluating 2 agents when model is ppo_gridnet

### ISSUE THREAD

**Issue by rahuldwivedi1112** [Farama-Foundation/MicroRTS-Py#119]
Error in ppo_gridnet_eval.py when model type is ppo_gridnet. Works fine with ppo_gridnet_large

Traceback (most recent call last):
  File "/home/rahul/MicroRTS-Py/experiments/ppo_gridnet_eval.py", line 116, in <module>
    envs = MicroRTSGridModeVecEnv(
  File "/home/rahul/MicroRTS-Py/gym_microrts/envs/vec_env.py", line 447, in __init__
    super(MicroRTSGridModeSharedMemVecEnv, self).__init__(
  File "/home/rahul/MicroRTS-Py/gym_microrts/envs/vec_env.py", line 144, in __init__
    self.start_client()
  File "/home/rahul/MicroRTS-Py/gym_microrts/envs/vec_env.py", line 473, in start_client
    from ts import JNIGridnetSharedMemVecClient as Client
ImportError: cannot import name 'JNIGridnetSharedMemVecClient' from 'tests' (unknown location)

**Comment by DennisSoemers** [comment]
With my latest merge into the master branch, this should be fixed.
