### ISSUE TITLE
Issue on petting_zoo_api

### ISSUE THREAD

**Issue by Dario-B0** [Farama-Foundation/MicroRTS-Py#132]
I get the following error only when i try to use the example for the petting_zoo_api in hello_world_pettingzoo.py : 

> Traceback (most recent call last):
>   File "/home/dario/Desktop/progetto_RL/MicroRTS-Py/hello_world_pettingzoo.py", line 76, in <module>
>     main()
>   File "/home/dario/Desktop/progetto_RL/MicroRTS-Py/hello_world_pettingzoo.py", line 51, in main
>     env = PettingZooMicroRTSGridModeSharedMemVecEnv(2, 0, ai2s=opponents)
>   File "/home/dario/Desktop/progetto_RL/MicroRTS-Py/gym_microrts/petting_zoo_api.py", line 33, in __init__
>     super(AECEnv, self).__init__(
>   File "/home/dario/Desktop/progetto_RL/MicroRTS-Py/gym_microrts/envs/vec_env.py", line 453, in __init__
>     super(MicroRTSGridModeSharedMemVecEnv, self).__init__(
>   File "/home/dario/Desktop/progetto_RL/MicroRTS-Py/gym_microrts/envs/vec_env.py", line 144, in __init__
>     self.start_client()
>   File "/home/dario/Desktop/progetto_RL/MicroRTS-Py/gym_microrts/envs/vec_env.py", line 479, in start_client
>     from ts import JNIGridnetSharedMemVecClient as Client
> ImportError: cannot import name 'JNIGridnetSharedMemVecClient' from 'tests' (unknown location)

**Comment by DennisSoemers** [comment]
I've never worked with the PettingZoo API myself, but it looks like it's trying to use `MicroRTSGridModeSharedMemVecEnv` instead of simply `MicroRTSGridModeVecEnv`. In one of his last commits before I unofficially sort of "took over", @vwxyzjn seems to have retired the shared mem env. Not sure if temporarily or permanently, see: https://github.com/Farama-Foundation/MicroRTS-Py/pull/104#discussion_r1211906907

So, I guess the obvious solution would be to switch the PettingZoo API over to using the non-shared-mem environment, but I'm not 100% sure whether this is as simple as changing the import, or if it will also require more work inside the Petting Zoo API.
